### PR TITLE
Correct name for the sonos logo for inky

### PR DESCRIPTION
**Pull request by Shadester**

### CODE REVIEW

**Review by hankhank10 — DISMISSED** [review]

**Review by hankhank10 — COMMENTED** [review]
Thank you for this.

I don't really like the filename being .png_inverted as it means it can't be viewed using a standard image editor.

I am going to incorporate the following code to fix this:

    if inverted:
        img_file = img_file.strip (".png")
        img_file = img_file+"-inverted.png"

**Review by hankhank10 — COMMENTED** [review]
I prefer to keep the inverted setting in ink_printer rather than sonos_settings as ink_printer is used by both the sonos and lastfm integrations. It's also where the "rotation" flag is set.

**Comment by hankhank10** [comment]
I have incorporated the key comments here into the master.

Would be great if you could have a look at the updated code and check it works how you intended. If not please do raise another request.

Appreciate your input - this is a definite improvement!

**Comment by Shadester** [comment]
Looks good. I would probably have all the settings (even for last_fm) in one settings file, so people easier can find what to change if they want the inverted or not. But looks good.

**Pull request closed without merging**
