### PR TITLE
Detect TV or Line-In sources

### LINKED ISSUE #30: feature request: turn screen off when source is line_in
hello!

I've tried poking around to add this, but I think I'm in way over my head. 

I'm using this setup in my family room, and when we watch TV at night the display shows the album art of the last album we were listening to all night and at peak brightness. it would be preferable if there was an option to turn the screen off when the source is detected as "line_in". 

The state of my system when watching TV looks like this (I crossed out the RINCON value, not sure what that is exactly):

`{
"volume":21,
"mute":false,
"equalizer":
{
"bass":0,
"treble":0,
"loudness":true,
"speechEnhancement":true,
"nightMode":false
},
"currentTrack":
{
"duration":0,
"uri":"x-sonos-htastream:RINCON_XXXXXXXXXXXXXXXXXX:spdif",
"trackUri":"x-sonos-htastream:RINCON_XXXXXXXXXXXXXXXXXX:spdif",
"type":"line_in",
"stationName":""
}
"nextTrack":
{
"artist":"",
"title":"",
"album":"",
"albumArtUri":"",
"duration":0,
"uri":""
},
"trackNo":1,
"elapsedTime":4101,
"elapsedTimeFormatted":"01:08:21",
"playbackState":"PLAYING",
"playMode":
{
"repeat":"none",
"shuffle":false,
"crossfade":false
},
"sub":
{
"gain":6,
"crossover":0,
"polarity":0,
"enabled":true
}
}`

### PR DESCRIPTION
**Pull request by jjlawren**
Detects TV or Line-In sources on devices that support those features. Displays appropriate icons on the display in those cases.

I was able to test with a Beam but I had to make some guesses on how it would work on an Amp, Connect, Five, or Play:5. Would appreciate if anyone with access to those could give a quick sanity check.

cc: @habra-cadabra @v1nc3lx

Fixes: https://github.com/hankhank10/music-screen-api/issues/30

### CODE REVIEW

**Comment by v1nc3lx** [comment]
Five here!
image

**Comment by v1nc3lx** [comment]
2020-08-09 09:48:14,690    INFO - Monitoring room: Soggiorno
2020-08-09 09:48:14,714    INFO - New track: Smooth Jazz 24/7 - Fourplay - Cinnamon Sugar [Smooth Jazz 24/7]
2020-08-09 09:48:14,716   ERROR - Task exception was never retrieved
future: <Task finished coro=<main() done, defined at /home/pi/dev/music-screen-api/go_sonos_highres.py:148> exception=NameError("name 'self' is not defined")>
Traceback (most recent call last):
  File "/home/pi/dev/music-screen-api/go_sonos_highres.py", line 191, in main
    await redraw(session, sonos_data, display)
  File "/home/pi/dev/music-screen-api/go_sonos_highres.py", line 89, in redraw
    if sonos_settings.demaster and self.type not in ["line_in", "TV"]:
NameError: name 'self' is not defined

**Comment by v1nc3lx** [comment]
> if sonos_settings.demaster and self.type not in ["line_in", "TV"]: ("go_sonos_highres.py" line 89 of 213 )

I had to switch "self.type" with "sonos_data.type" to make it work (?!)
anyway.. it works!! 👍  
Just one thing about "show_details": when i switched to line-in, it still displayed infos about the previous track

image

**Comment by jjlawren** [comment]
Oops, typo. Thanks for testing! I'll try to find time to fix both of those later today.

**Comment by jjlawren** [comment]
@v1nc3lx pushed an update, can you give a test? Didn't have a lot of time to test but this seems like a straightforward change.

**Comment by habra-cadabra** [comment]
looks good on Sonos Arc! 

IMG_1769

**Comment by v1nc3lx** [comment]
Five here!

image

**Comment by v1nc3lx** [comment]
switching to line-in -> wait -> screen turns off -> wait -> start radio: screen turns on with line-in picture and after a couple of seconds it switches to radio picture

**Comment by jjlawren** [comment]
I'm not totally clear on the timing in that sequence of events. It might be a limitation of the Sonos API if there's a slight delay.

**Pull request merged**
